"""
(Generated by AI) Test script to see how the scraper processes a URL
Usage: python3 test_scraper_url.py <url>
"""

import sys
import requests
from bs4 import BeautifulSoup
import re
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from collections import defaultdict

def test_scraper_url(url):
    """Test the scraper on a URL"""
    
    print("="*80)
    print(f"Fetching URL: {url}")
    print("="*80)
    
    # Fetch the URL
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        html = response.text
        print("✓ Successfully fetched page")
    except Exception as e:
        print(f"ERROR fetching URL: {e}")
        return
    
    # Initialize stemmer
    ps = PorterStemmer()
    
    # Parse HTML
    soup = BeautifulSoup(html, "html.parser")
    
    # Remove noise
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()
    
    # ===== TITLE PROCESSING =====
    print("\n" + "="*80)
    print("TITLE PROCESSING")
    print("="*80)
    
    title_counts = defaultdict(int)
    if soup.title and soup.title.string:
        title = soup.title.string.strip()
        print(f"Raw title: '{title}'")
        print("\nTokens from title:")
        
        for tok in word_tokenize(title):
            tok_lower = tok.lower()
            if re.fullmatch(r"[a-z0-9]+", tok_lower):
                stem = ps.stem(tok_lower)
                title_counts[stem] += 1
                print(f"  '{tok}' -> '{tok_lower}' -> stem: '{stem}'")
            else:
                print(f"  '{tok}' -> '{tok_lower}' -> FILTERED (doesn't match regex)")
        
        print(f"\nTitle stems: {dict(title_counts)}")
    else:
        print("No title found!")
    
    # ===== HEADER/BOLD PROCESSING =====
    print("\n" + "="*80)
    print("HEADER/BOLD PROCESSING")
    print("="*80)
    
    header_nodes = soup.find_all(["h1","h2","h3","h4","h5","h6","b","strong"])
    header_counts = defaultdict(int)
    
    if header_nodes:
        print(f"Found {len(header_nodes)} header/bold elements")
        print("\nFirst 10 header/bold elements:")
        
        for i, node in enumerate(header_nodes[:10]):
            htext = node.get_text(separator=" ", strip=True)
            print(f"\n  [{i+1}] <{node.name}>: '{htext[:80]}{'...' if len(htext) > 80 else ''}'")
        
        # Process all headers
        for node in header_nodes:
            htext = node.get_text(separator=" ", strip=True)
            for tok in word_tokenize(htext):
                tok_lower = tok.lower()
                if re.fullmatch(r"[a-z0-9]+", tok_lower):
                    stem = ps.stem(tok_lower)
                    header_counts[stem] += 1
        
        # Show top 20 header stems
        top_headers = sorted(header_counts.items(), key=lambda x: x[1], reverse=True)[:20]
        print(f"\nTop 20 header/bold stems:")
        for stem, count in top_headers:
            print(f"  '{stem}': {count}")
    else:
        print("No header/bold elements found!")
    
    # ===== BODY TEXT PROCESSING =====
    print("\n" + "="*80)
    print("BODY TEXT PROCESSING")
    print("="*80)
    
    full_text = soup.get_text(separator=" ", strip=True)
    full_text = re.sub(r"\s+", " ", full_text)
    
    print(f"Body text length: {len(full_text)} characters")
    print(f"Body text preview: '{full_text[:200]}...'")
    
    tokens = word_tokenize(full_text)
    freq_map = defaultdict(int)
    pos_map = defaultdict(list)
    
    for pos, token in enumerate(tokens):
        token_lower = token.lower()
        if re.fullmatch(r"[a-z0-9]+", token_lower):
            stem = ps.stem(token_lower)
            freq_map[stem] += 1
            pos_map[stem].append(pos)
    
    print(f"\nTotal tokens: {len(tokens)}")
    print(f"Unique stems: {len(freq_map)}")
    
    # Show top 20 most frequent stems
    top_stems = sorted(freq_map.items(), key=lambda x: x[1], reverse=True)[:20]
    print(f"\nTop 20 most frequent body stems:")
    for stem, count in top_stems:
        print(f"  '{stem}': {count} occurrences")
    
    # ===== FINAL OUTPUT =====
    print("\n" + "="*80)
    print("FINAL OUTPUT (Combined)")
    print("="*80)
    
    output = {}
    all_stems = set(freq_map.keys()) | set(title_counts.keys()) | set(header_counts.keys())
    
    for stem in all_stems:
        output[stem] = {
            "freq": freq_map.get(stem, 0),
            "positions": pos_map.get(stem, []),
            "header_bold_count": header_counts.get(stem, 0),
            "title_count": title_counts.get(stem, 0)
        }
    
    print(f"Total unique stems in output: {len(output)}")
    
    # ===== SEARCH FOR SPECIFIC TERMS =====
    print("\n" + "="*80)
    print("SEARCH FOR SPECIFIC TERMS")
    print("="*80)
    
    search_terms = ["cristina", "lopes", "lopez", "professor", "software"]
    
    for term in search_terms:
        stem = ps.stem(term.lower())
        print(f"\nSearching for '{term}' (stem: '{stem}'):")
        
        if stem in output:
            data = output[stem]
            print(f"  ✓ FOUND!")
            print(f"    Body frequency: {data['freq']}")
            print(f"    Title count: {data['title_count']}")
            print(f"    Header/Bold count: {data['header_bold_count']}")
            if data['positions']:
                print(f"    First 5 positions: {data['positions'][:5]}")
        else:
            print(f"  ✗ NOT FOUND in document")
    
    # ===== ALLOW USER TO SEARCH =====
    print("\n" + "="*80)
    print("INTERACTIVE SEARCH")
    print("="*80)
    print("Enter terms to search for (or 'q' to quit):")
    
    while True:
        user_term = input("\nSearch term: ").strip()
        if user_term.lower() == 'q':
            break
        
        if not user_term:
            continue
        
        stem = ps.stem(user_term.lower())
        print(f"Searching for '{user_term}' (stem: '{stem}'):")
        
        if stem in output:
            data = output[stem]
            print(f"  ✓ FOUND!")
            print(f"    Body frequency: {data['freq']}")
            print(f"    Title count: {data['title_count']}")
            print(f"    Header/Bold count: {data['header_bold_count']}")
            print(f"    Total positions: {len(data['positions'])}")
            if data['positions']:
                print(f"    First 10 positions: {data['positions'][:10]}")
        else:
            print(f"  ✗ NOT FOUND in document")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 test_scraper_url.py <url>")
        print("\nExample:")
        print("  python3 test_scraper_url.py https://www.informatics.uci.edu/explore/faculty-profiles/cristina-lopes/")
        sys.exit(1)
    
    url = sys.argv[1]
    test_scraper_url(url)